apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: innovatemart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: ghcr.io/aws-samples/retail-store-sample-catalog:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: innovatemart
spec:
  selector:
    app: catalog
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
