apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: innovatemart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: ghcr.io/aws-samples/retail-store-sample-checkout:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: innovatemart
spec:
  selector:
    app: checkout
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
