apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: innovatemart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: ghcr.io/aws-samples/retail-store-sample-orders:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: innovatemart
spec:
  selector:
    app: orders
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
