apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: innovatemart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: ghcr.io/aws-samples/retail-store-sample-ui:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: innovatemart
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
