name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name innovatemart-cluster

    - name: Deploy manifests
      run: |
        kubectl apply -f src/ui/ui-deployment.yaml
        kubectl apply -f src/catalog/catalog-deployment.yaml
        kubectl apply -f src/carts/carts-deployment.yaml
        kubectl apply -f src/orders/orders-deployment.yaml
        kubectl apply -f src/checkout/checkout-deployment.yaml
        kubectl apply -f src/payment/payment-deployment.yaml
        kubectl apply -f src/notification/notification-deployment.yaml
